# Cambiar el puerto para evitar conflicto con el 8080
server.port=8081

# Configuración H2 Database y JPA (Modo archivo para persistencia de datos)
spring.datasource.url=jdbc:h2:file:./data/veterinariadb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
